# Generated by Django 5.0.1 on 2024-02-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, help_text='Name of our Clients or Customer', max_length=50, null=True)),
                ('customer_email', models.EmailField(blank=True, help_text='Email of our Clients or Customer', max_length=100, null=True)),
                ('customer_phone', models.CharField(blank=True, help_text='Phone Number of our Clients or Customer', max_length=20, null=True)),
                ('customer_address', models.CharField(blank=True, help_text='Address of our Clients or Customer', max_length=150, null=True)),
                ('customer_category', models.CharField(blank=True, help_text='Category of our Client or Customer', max_length=20, null=True)),
                ('customer_joined_yr', models.IntegerField(blank=True, help_text='Year when Client or Customer has joined us', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
